### ISSUE TITLE
EmoVIT training weight relaese 

### ISSUE THREAD

**Issue by Longtime1994** [aimmemotion/EmoVIT#2]
Hello, first of all thank you for your amazing work!

I wonder if you have any plans for open-sourcing the model weight mentioned in the paper.

Thank you for your attention on this issue.

**Comment by aimmemotion** [comment]
Hi, our training weight can be found in the "model_weights1.pth" in the LAVIS folder: https://drive.google.com/file/d/1YLgOVlJNIdyOOlppX0uPMXGxVT37YqbF/view?usp=drive_link
