### ISSUE TITLE
OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model"

### ISSUE THREAD

**Issue by kristen-ding** [aimmemotion/EmoVIT#3]
![image](https://github.com/aimmemotion/EmoVIT/assets/157441701/60fb9177-b6ae-4194-b67d-93cdf0d5ada6)

load_path = './EmoVIT/model_weights1.pth'
model = torch.load(load_path, map_location=torch.device('cpu'))

When conducting my tests, I encountered an OSError. How should I modify the default path?

**Comment by ditto66** [comment]
I have the same question. Can you pls help fix that? @tokenizer.mode

**Comment by ditto66** [comment]
I have the same question. Can you pls help fix that? @aimmemotion

**Comment by dazzleeee** [comment]
> I've encountered the same issue. I've gone through all the configuration files but couldn't find where it's being set. I hope to get an answer.

I find the dir in" ./model_weights1.pth",but I don't how to fix it.

**Comment by yutchina** [comment]
确实有问题 需要重新训练一个

**Comment by ditto66** [comment]
> 确实有问题 需要重新训练一个

Do you success running the training code?

I encountered the TypeError when I tried to retrain the model:

```
File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids
    ann[ key] = str(idx)
TypeError: list indices must be integers or slices, not str
```

**Comment by yutchina** [comment]
是的 我成功复现了 但是修改了很多代码

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/25/2024 14:36 |
| To | aimmemotion/EmoVIT ***@***.***> |
| Cc | yutchina ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) |

确实有问题 需要重新训练一个

Do you success running the training code?

I encountered the TypeError when I tried to retrain the model:

File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids
    ann[ key] = str(idx)
TypeError: list indices must be integers or slices, not str

**Comment by dazzleeee** [comment]
可以参考下你的代码嘛~

**Comment by ditto66** [comment]
> 是的 我成功复现了 但是修改了很多代码
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT ***@***.***> | | Cc | yutchina ***@***.***>, Comment ***@***.***> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

If you don't mind, could you please share the code? 
We would really appreciate it.

> 是的 我成功复现了 但是修改了很多代码
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT ***@***.***> | | Cc | yutchina ***@***.***>, Comment ***@***.***> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

If you don't mind, could you please share the code? 
We would really appreciate it.

**Comment by ditto66** [comment]
> 是的 我成功复现了 但是修改了很多代码
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT ***@***.***> | | Cc | yutchina ***@***.***>, Comment ***@***.***> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

If you don't mind, could you please share the code? 
We would really appreciate it.

**Comment by yutchina** [comment]
> > 是的 我成功复现了 但是修改了很多代码
> > […](#)
> > ---- Replied Message ---- | From | _**@**_._**> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT _**@**_.**_> | | Cc | yutchina _**@**_._**>, Comment _**@**_.**_> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> If you don't mind, could you please share the code? We would really appreciate it.

这花费了我很多精力和算力资源 所以我更倾向于合作

**Comment by kristen-ding** [comment]
> 是的 我成功复现了 但是修改了很多代码
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT ***@***.***> | | Cc | yutchina ***@***.***>, Comment ***@***.***> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Can you share your code, thanks.

**Comment by ditto66** [comment]
> > > 是的 我成功复现了 但是修改了很多代码
> > > […](#)
> > > ---- Replied Message ---- | From | _**@**_._**> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT _**@**_.**_> | | Cc | yutchina _**@**_._**>, Comment _**@**_.**_> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > If you don't mind, could you please share the code? We would really appreciate it.
> 
> 这花费了我很多精力和算力资源 所以我更倾向于合作

Just asking that how do these multiple conversation data being used in trainig? (e.g., by concanating them in text_input or treat each question as a sample?)

**Comment by JoJoistheBestOne** [comment]
it's a pretty that the talented work is shared with open source but with some trivial mistakes..

**Comment by kristen-ding** [comment]
![image](https://github.com/user-attachments/assets/32165a20-d68e-4b63-9d55-67ca0082a0f1)
I solved it using this.

**Comment by hyumiao** [comment]
> > > 是的 我成功复现了 但是修改了很多代码
> > > […](#)
> > > ---- Replied Message ---- | From | _**@**_._**> | | Date | 09/25/2024 14:36 | | To | aimmemotion/EmoVIT _**@**_.**_> | | Cc | yutchina _**@**_._**>, Comment _**@**_.**_> | | Subject | Re: [aimmemotion/EmoVIT] OSError: Not found: "/mnt/data0/Garmin/LAVIS/lavis/weight/vicuna-7b-2/tokenizer.model" (Issue #3) | 确实有问题 需要重新训练一个 Do you success running the training code? I encountered the TypeError when I tried to retrain the model: File "EmoVIT/LAVIS/lavis/datasets/datasets/base_dataset.py", line 47, in _add_instance_ids ann[ key] = str(idx) TypeError: list indices must be integers or slices, not str — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > If you don't mind, could you please share the code? We would really appreciate it.
> 
> 这花费了我很多精力和算力资源 所以我更倾向于合作

您好，请问一下您在复现重新训练代码时，使用的设备是什么啊？我自己训练时会遇到OOM问题
